// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CreateInspectionTeam-Duplicate', function () {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function () {
        await driver.quit()
    })
    it('CreateInspectionTeam-Duplicate', async function () {
        await driver.get('http://127.0.0.1:5500/View/index.html')
        await driver.findElement(By.linkText('Manage Teams')).click()
        await driver.findElement(By.id('teamName')).click()
        await driver.findElement(By.id('teamName')).sendKeys('Team Alpha')
        await driver
            .findElement(By.xpath("//button[contains(.,\'Add Team\')]"))
            .click()
        await driver.wait(
            until.elementTextIs(
                await driver.findElement(By.id('message')),
                'Error adding team, the identifiers must be unique.'
            ),
            30000
        )
        assert(
            (await driver.findElement(By.id('message')).getText()) ==
                'Error adding team, the identifiers must be unique.'
        )
    })
})
