// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC11', function () {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function () {
        await driver.quit()
    })
    it('TC11', async function () {
        await driver.get('http://127.0.0.1:5500/View/index.html')
        await driver.manage().window().setRect({ width: 974, height: 1080 })
        await driver.findElement(By.linkText('Edit Documents')).click()
        await driver.findElement(By.css('#document_5 .trash_img')).click()
        await driver.findElement(By.id('editable')).click()
        await driver
            .findElement(By.id('Inspected_lateness_input'))
            .sendKeys('0')
        await driver.findElement(By.id('editable')).click()
        await driver
            .findElement(By.id('Student_attendance_input'))
            .sendKeys('100')
        await driver.findElement(By.id('editable')).click()
        await driver
            .findElement(By.id('Room_adaptation_input'))
            .sendKeys('Well adapted')
        await driver.findElement(By.id('editable')).click()
        await driver
            .findElement(By.id('Content_compatibility_input'))
            .sendKeys('5')
        await driver.findElement(By.id('editable')).click()
        await driver
            .findElement(By.id('Substantive_assessment_input'))
            .sendKeys('Good')
        await driver.findElement(By.id('editable')).click()
        await driver.findElement(By.id('Final_assessment_input')).sendKeys('5')
        await driver.findElement(By.id('buttonSave')).click()
        await driver.findElement(By.css('.save_popup_btn')).click()
        await driver.findElement(By.css('.ok_popup_btn')).click()
    })
})
