// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC13', function () {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function () {
        await driver.quit()
    })
    it('TC13', async function () {
        await driver.get('http://127.0.0.1:5500/View/index.html')
        await driver.manage().window().setRect({ width: 974, height: 1080 })
        await driver.findElement(By.linkText('Edit Documents')).click()
        await driver.findElement(By.css('#document_5 .trash_img')).click()
        await driver.findElement(By.id('editable')).click()
        await driver.findElement(By.id('editable')).click()
        await driver.findElement(By.id('Room_adaptation_input')).click()
        await driver.findElement(By.id('Room_adaptation_input')).click()
        {
            const element = await driver.findElement(
                By.id('Room_adaptation_input')
            )
            await driver
                .actions({ bridge: true })
                .doubleClick(element)
                .perform()
        }
        await driver.findElement(By.id('Room_adaptation_input')).click()
        await driver.findElement(By.id('Content_compatibility_input')).click()
        await driver.findElement(By.id('Substantive_assessment_input')).click()
        await driver.findElement(By.id('Substantive_assessment_input')).click()
        {
            const element = await driver.findElement(
                By.id('Substantive_assessment_input')
            )
            await driver
                .actions({ bridge: true })
                .doubleClick(element)
                .perform()
        }
        await driver.findElement(By.id('Final_assessment_input')).click()
        await driver.findElement(By.id('Recommendation_input')).click()
        await driver.findElement(By.id('Recommendation_input')).click()
        {
            const element = await driver.findElement(
                By.id('Recommendation_input')
            )
            await driver
                .actions({ bridge: true })
                .doubleClick(element)
                .perform()
        }
        await driver.findElement(By.id('Recommendation_input')).click()
        await driver.findElement(By.id('Recommendation_input')).sendKeys('0')
        await driver.findElement(By.id('buttonSave')).click()
        await driver.findElement(By.css('.cancel_popup_btn')).click()
    })
})
