// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC21', function () {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function () {
        await driver.quit()
    })
    it('TC21', async function () {
        await driver.get('http://127.0.0.1:5500/View/index.html')
        await driver.manage().window().setRect({ width: 974, height: 1080 })
        await driver
            .findElement(By.linkText('Edit/Delete Inspection Terms'))
            .click()
        await driver
            .findElement(By.css('li:nth-child(1) .edit_button > .trash_img'))
            .click()
        await driver.findElement(By.id('datePicker')).click()
        await driver.findElement(By.id('teamPicker')).click()
        {
            const dropdown = await driver.findElement(By.id('teamPicker'))
            await dropdown
                .findElement(
                    By.xpath(
                        "//option[. = 'Team Gamma mgr inż Michael Wilson dr hab Sarah Taylor dr hab Chris Martin']"
                    )
                )
                .click()
        }
        await driver.findElement(By.id('buttonSave')).click()
        await driver.findElement(By.css('.cancel_popup_btn')).click()
    })
})
