// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC26', function () {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function () {
        await driver.quit()
    })
    it('TC26', async function () {
        await driver.get('http://127.0.0.1:5500/View/index.html')
        await driver.manage().window().setRect({ width: 974, height: 1080 })
        await driver
            .findElement(By.linkText('Edit/Delete Inspection Terms'))
            .click()
        await driver
            .findElement(By.css('li:nth-child(5) .edit_button > .trash_img'))
            .click()
        {
            const element = await driver.findElement(
                By.css('li:nth-child(5) .edit_button > .trash_img')
            )
            await driver
                .actions({ bridge: true })
                .moveToElement(element)
                .perform()
        }
        {
            const element = await driver.findElement(By.CSS_SELECTOR, 'body')
            await driver
                .actions({ bridge: true })
                .moveToElement(element, 0, 0)
                .perform()
        }
        await driver.findElement(By.css('.ok_popup_btn')).click()
    })
})
