// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('ViewInspectionTeams', function () {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function () {
        await driver.quit()
    })
    it('ViewInspectionTeams', async function () {
        await driver.get('http://127.0.0.1:5500/View/index.html')
        await driver.findElement(By.linkText('Manage Teams')).click()
        await driver.wait(
            until.elementLocated(By.xpath("//h2[contains(.,\'Team Alpha\')]")),
            3000
        )
        {
            const elements = await driver.findElements(
                By.xpath("//li[contains(.,\'mgr John Doe        Delete 🗑️\')]")
            )
            assert(elements.length)
        }
        {
            const elements = await driver.findElements(
                By.xpath("//li[contains(.,\'dr Jane Smith       Delete 🗑️\')]")
            )
            assert(elements.length)
        }
        {
            const elements = await driver.findElements(
                By.xpath("//li[contains(.,\'profesor David WhiteDelete 🗑️\')]")
            )
            assert(elements.length)
        }
    })
})
