// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('ViewInspectionTeams-Empty', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('ViewInspectionTeams-Empty', async function() {
    await driver.get("http://127.0.0.1:5500/View/index.html")
    await driver.findElement(By.linkText("Manage Teams")).click()
    await driver.wait(until.elementLocated(By.xpath("//h2[contains(.,\'Team Foxtrot\')]")), 30000)
    assert(await driver.findElement(By.css("p:nth-child(1)")).getText() == "No members in this team.")
  })
})
